services:
  - type: web
    name: rd-health-club
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /admin
        destination: /admin.html
