services:
  - type: web
    name: rd-health-club
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    disk:
      name: cms-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
